<a href="https://colab.research.google.com/github/gustavocoderjs/An-lise-de-Dados-/blob/main/medical_cost_personal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("mirichoi0218/insurance")

print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/insurance

In [2]:
import os

# Listar arquivos dentro da pasta
print(os.listdir(path))

['insurance.csv']

In [4]:
import pandas as pd

file_path = os.path.join(path, 'insurance.csv')
df = pd.read_csv(file_path)
print(df.head())

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [8]:
df['age'].value_counts(normalize=True)

age
18    0.051570
19    0.050822
46    0.021674
52    0.021674
50    0.021674
47    0.021674
48    0.021674
51    0.021674
45    0.021674
20    0.021674
24    0.020927
27    0.020927
28    0.020927
25    0.020927
23    0.020927
49    0.020927
54    0.020927
53    0.020927
22    0.020927
21    0.020927
26    0.020927
31    0.020179
41    0.020179
44    0.020179
43    0.020179
42    0.020179
29    0.020179
30    0.020179
40    0.020179
32    0.019432
33    0.019432
57    0.019432
34    0.019432
55    0.019432
56    0.019432
35    0.018685
58    0.018685
37    0.018685
59    0.018685
39    0.018685
36    0.018685
38    0.018685
62    0.017190
60    0.017190
63    0.017190
61    0.017190
64    0.016442
Name: proportion, dtype: float64

In [7]:
df.sample(10)

      age     sex     bmi  children smoker     region      charges
191    36  female  26.200         0     no  southwest   4883.86600
11     62  female  26.290         0    yes  southeast  27808.72510
502    51    male  23.210         1    yes  southeast  22218.11490
1258   55    male  37.715         3     no  northwest  30063.58055
1056   48  female  28.900         0     no  southwest   8277.52300
357    47    male  29.830         3     no  northwest   9620.33070
203    27  female  36.080         0    yes  southeast  37133.89820
478    21    male  36.850         0     no  southeast   1534.30450
124    47  female  33.915         3     no  northwest  10115.00885
667    40  female  32.775         2    yes  northwest  40003.33225

In [9]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Melhor visualização dos gráficos
sns.set(style="whitegrid")

In [11]:
df.shape         # Linhas e colunas

(1338, 7)

In [12]:
df.columns       # Nomes das colunas

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [13]:
df.info()        # Tipos de dados e valores nulos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [14]:
df.describe()    # Estatísticas para colunas numéricas

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010